// Compile check only: every platform-neutral contract and module header builds
// natively, together, with nothing else included first. The headers that hold
// GPU objects (residency/upload.h) build in the wasm configuration only.

#include "core/arch/architecture.h"
#include "core/cache/kv.h"
#include "core/cache/prefix.h"
#include "core/capability/capability.h"
#include "core/formats/device_layout.h"
#include "core/formats/format.h"
#include "core/gguf/arrays.h"
#include "core/gguf/index.h"
#include "core/kernels/gather/gather.h"
#include "core/kernels/interface.h"
#include "core/kernels/norm/norm.h"
#include "core/kernels/rope/rope.h"
#include "core/model/model_description.h"
#include "core/policy/policy.h"
#include "core/preflight/preflight.h"
#include "core/residency/piece_writer.h"
#include "core/residency/plan.h"
#include "core/residency/routes.h"
#include "core/residency/weight_view.h"
#include "core/runtime/runtime.h"
#include "core/sampler/sampler.h"
#include "core/tokenizer/bpe/byte_level_bpe.h"
#include "core/tokenizer/bpe/byte_map.h"
#include "core/tokenizer/bpe/merge.h"
#include "core/tokenizer/bpe/merge_table.h"
#include "core/tokenizer/bpe/piece_cache.h"
#include "core/tokenizer/bpe/sentencepiece_bpe.h"
#include "core/tokenizer/bpe/sentencepiece_merges.h"
#include "core/tokenizer/load.h"
#include "core/tokenizer/nfc.h"
#include "core/tokenizer/pretokenize.h"
#include "core/tokenizer/special.h"
#include "core/tokenizer/tokenizer.h"
#include "core/tokenizer/unicode.h"
#include "core/tokenizer/unicode_tables.h"
#include "core/tokenizer/vocabulary.h"
