// llama.cpp's logits for a pinned prompt, on its CPU backend and on Metal,
// written as the C++ fixture tests/gpu/reference_test.cpp reads. A
// development tool, run by tools/make_reference_logits.sh; never part of the
// harness.
//
// The prompt is decoded a token at a time, as the test decodes it. At each
// position it records Metal's 20 most likely tokens, their logits from both
// backends, and each backend's log-sum-exp over the whole vocabulary, in
// double. Floats are written as hexadecimal literals, so the fixture holds
// llama.cpp's values exactly.
//
//     reference_logits <model.gguf> <llama.cpp commit> <model sha256> <tokens> <text>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <numeric>
#include <string>
#include <vector>

#include "llama.h"

namespace {

constexpr int kTop = 20;

struct Backend {
    llama_model* model;
    llama_context* context;
};

Backend open(const char* path, bool cpu) {
    llama_model_params mp = llama_model_default_params();
    static ggml_backend_dev_t no_devices[] = {nullptr};
    if (cpu) {
        mp.devices = no_devices;   // the CPU alone
        mp.n_gpu_layers = 0;
    } else {
        mp.n_gpu_layers = -1;      // every layer on Metal
    }
    llama_model* model = llama_model_load_from_file(path, mp);
    if (model == nullptr) std::exit(1);
    llama_context_params cp = llama_context_default_params();
    cp.n_ctx = 256;
    cp.n_batch = 64;
    if (cpu) {
        cp.offload_kqv = false;
        cp.op_offload = false;
    }
    llama_context* context = llama_init_from_model(model, cp);
    if (context == nullptr) std::exit(1);
    return {model, context};
}

// Decodes `token` and returns the vocabulary's logits after it.
std::vector<float> step(const Backend& b, llama_token token, int vocabulary) {
    if (llama_decode(b.context, llama_batch_get_one(&token, 1)) != 0) std::exit(1);
    const float* logits = llama_get_logits_ith(b.context, -1);
    return {logits, logits + vocabulary};
}

double log_sum_exp(const std::vector<float>& logits) {
    const double top = *std::max_element(logits.begin(), logits.end());
    double sum = 0;
    for (const float l : logits) sum += std::exp(static_cast<double>(l) - top);
    return top + std::log(sum);
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 6) {
        std::fprintf(stderr, "usage: reference_logits <model.gguf> <commit> <sha256> <tokens> <text>\n");
        return 2;
    }
    const int count = std::atoi(argv[4]);
    llama_backend_init();
    const Backend cpu = open(argv[1], true), metal = open(argv[1], false);
    const llama_vocab* vocab = llama_model_get_vocab(metal.model);
    const int vocabulary = llama_vocab_n_tokens(vocab);

    const std::string text = argv[5];
    std::vector<llama_token> tokens(text.size() + 8);
    const int n = llama_tokenize(vocab, text.data(), static_cast<int>(text.size()), tokens.data(),
                                 static_cast<int>(tokens.size()), true, false);
    if (n < count) {
        std::fprintf(stderr, "the text is %d tokens, fewer than %d\n", n, count);
        return 1;
    }
    tokens.resize(count);

    std::printf("// Generated by tools/make_reference_logits.sh. Do not edit.\n");
    std::printf("// llama.cpp %s, CPU and Metal, on the model of SHA-256 %s.\n", argv[2], argv[3]);
    std::printf("// Each position: Metal's %d most likely tokens, their logits on Metal and on\n", kTop);
    std::printf("// the CPU, and each backend's log-sum-exp over the vocabulary.\n");
    std::printf("inline constexpr std::string_view kReferenceSha256 = \"%s\";\n", argv[3]);
    std::printf("inline constexpr std::uint32_t kReferenceVocabulary = %d;\n", vocabulary);
    std::printf("inline constexpr std::uint32_t kReferenceTokens[] = {");
    for (int i = 0; i < count; ++i) std::printf("%s%d", i ? ", " : "", tokens[i]);
    std::printf("};\n");
    std::printf("inline constexpr ReferencePosition kReferencePositions[] = {\n");
    for (int i = 0; i < count; ++i) {
        const std::vector<float> m = step(metal, tokens[i], vocabulary), c = step(cpu, tokens[i], vocabulary);
        std::vector<int> order(vocabulary);
        std::iota(order.begin(), order.end(), 0);
        std::partial_sort(order.begin(), order.begin() + kTop, order.end(),
                          [&](int a, int b) { return m[a] > m[b] || (m[a] == m[b] && a < b); });
        std::printf("    {%a, %a, {", log_sum_exp(m), log_sum_exp(c));
        for (int k = 0; k < kTop; ++k) std::printf("%s%d", k ? ", " : "", order[k]);
        std::printf("}, {");
        for (int k = 0; k < kTop; ++k) std::printf("%s%af", k ? ", " : "", m[order[k]]);
        std::printf("}, {");
        for (int k = 0; k < kTop; ++k) std::printf("%s%af", k ? ", " : "", c[order[k]]);
        std::printf("}},\n");
    }
    std::printf("};\n");

    for (const Backend* b : {&cpu, &metal}) {
        llama_free(b->context);
        llama_model_free(b->model);
    }
    llama_backend_free();
    return 0;
}
